language: node_js
node_js:
- "lts/*"

os:
  - linux

branches:
  except:
    - gh-pages

cache: yarn

stages:
- build
- test
- coverage
- deploy

jobs:
  include:
    - stage: build
      script:
        - yarn run build
    - stage: test
      script: yarn run test
    - stage: coverage
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: yarn run coverage
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
        - ./cc-test-reporter after-build
    - stage: deploy
      if: tag IS present
      script:
        - yarn run build
        - yarn pack
        - yarn run doc
      deploy:
      - provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: ./doc/
        skip_cleanup: true
        keep_history: true
        on:
          tags: true
      - provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file_glob: true
        file: find-files-by-patterns-*.tgz
        on:
          tags: true
      - provider: npm
        email: ouimetmarcantoine@gmail.com
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - ouimetmarcantoine@gmail.com
