os:
- linux
- osx
language: node_js
node_js:
- node
- "10"
- "8"
- "6"
stages:
- build
- test
- coverage
- name: deploy
  if: branch = master AND tag = true
jobs:
  include:
    - stage: build
      os: linux
      node_js: "10"
      script:
        - yarn run build
    - stage: test
      script: yarn run test
    - stage: coverage
      os: linux
      node_js: "10"
      script: yarn run coverage
      after_success: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
    - stage: deploy
      os: linux
      node_js: "10"
      script:
        - yarn run build
        - yarn pack
        - yarn run doc
      deploy:
      - provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: ./doc/
        keep-history: true
        skip_cleanup: true
      - provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: find-files-by-patterns-*.tgz
        skip_cleanup: true
      - provider: npm
        email: ouimetmarcantoine@gmail.com
        api_key: $NPM_TOKEN
        skip_cleanup: true
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - ouimetmarcantoine@gmail.com
